import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from '../scripts/content.mjs';
import { testDesktopPlayback } from './desktop-playback.mjs';
fs.mkdirSync(path.join(ROOT, '.test-data'), { recursive: true });
fs.mkdirSync(path.join(ROOT, 'test-results'), { recursive: true });
const directory = fs.mkdtempSync(path.join(ROOT, '.test-data/e2e-'));
const exportPath = path.join(directory, 'export.json');
const invalidPath = path.join(directory, 'invalid.json');
fs.writeFileSync(invalidPath, JSON.stringify({ version: 1, progress: {}, sessions: [{ durationMs: -1 }] }));
// Electron must show its native window to deliver pointer input to cross-origin frames.
const env = { ...process.env, STUDY_DATA_DIR: directory, STUDY_HEADLESS: '0' }; delete env.ELECTRON_RUN_AS_NODE;
if (process.env.STUDY_TEST_EXE) env.PATH = `${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`;
const launch = () => electron.launch({ ...(process.env.STUDY_TEST_EXE ? { executablePath: process.env.STUDY_TEST_EXE, args: [] } : { args: [ROOT] }), env, timeout: 30000 });
let app = await launch();
let page = await app.firstWindow();
page.setDefaultTimeout(15000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.waitForSelector('.problem-table');
  await app.evaluate(({ BrowserWindow }) => { const win = BrowserWindow.getAllWindows()[0]; win.show(); win.focus(); });
  assert.equal(await page.locator('.problem-table tbody tr').count(), 255);
  console.log('PASS bundled library opens without external services');
  await app.evaluate(({ session }) => session.defaultSession.enableNetworkEmulation({ offline: true }));
  await page.getByRole('searchbox', { name: 'Search problems' }).fill('Two Sum');
  await page.getByRole('button', { name: 'Open Two Sum', exact: true }).click();
  const frame = page.frameLocator('iframe');
  await frame.locator('#btn-next').click();
  await frame.locator('#btn-next').click();
  assert.equal(await frame.locator('body').getAttribute('data-workspace-version'), '1');
  assert.equal(await frame.locator('body').evaluate(() => typeof window.study), 'undefined');
  assert.equal(await frame.locator('body').evaluate(() => typeof window.require), 'undefined');
  assert.equal(await frame.locator('body').evaluate(() => { try { return typeof parent.study; } catch { return 'isolated'; } }), 'isolated');
  assert.equal(await page.getByLabel('Problem progress').inputValue(), 'in-progress');
  await testDesktopPlayback(app, page);
  await frame.locator('summary').filter({ hasText: 'Examples' }).click();
  await frame.locator('.study-examples-menu[open]').waitFor();
  await frame.locator('#btn-ex-2').click();
  await frame.locator('summary').filter({ hasText: 'Custom input' }).click();
  await frame.locator('#custom-input').fill('3, 2, 4');
  await frame.locator('#target-input').fill('6');
  await frame.getByRole('button', { name: 'Load', exact: true }).click();
  await frame.locator('summary').filter({ hasText: 'Custom input' }).click();
  await frame.locator('#btn-next').click();
  await frame.locator('#btn-fullscreen').click();
  await page.waitForFunction(() => !!document.fullscreenElement);
  await page.evaluate(() => document.exitFullscreen());
  await page.getByRole('button', { name: 'Bookmark problem' }).click();
  await page.getByRole('button', { name: 'Needs review', exact: true }).click();
  await page.getByLabel('Problem progress').selectOption('completed');
  console.log('PASS offline visualizer, examples, custom input, isolation, bookmarks and progress');
  await page.getByRole('tab', { name: 'Notes', exact: true }).click();
  await page.getByRole('heading', { name: 'Variable Pattern' }).waitFor();
  await page.getByRole('tab', { name: /^History/ }).click();
  await page.getByRole('button', { name: 'Edit session', exact: true }).first().click();
  await page.getByLabel(/Time spent/).fill('12.5');
  await page.getByLabel('Outcome', { exact: true }).selectOption('solved');
  await page.getByLabel('Reflection', { exact: true }).fill('Check the complement before inserting into seen.');
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await page.getByText('Check the complement before inserting into seen.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Back to library' }).click();
  console.log('PASS notes, editable time, outcome and reflection');
  await page.getByRole('searchbox', { name: 'Search problems' }).fill('933');
  await page.getByRole('button', { name: 'Open Number of Recent Calls', exact: true }).click();
  await page.getByRole('tab', { name: 'Visualizer', exact: true }).click();
  const recentFrame = page.frameLocator('iframe[title="Number of Recent Calls visualizer"]');
  await recentFrame.locator('#study-object-view').waitFor();
  assert.ok(await recentFrame.locator('[data-study-panel=objects]').isVisible());
  assert.ok(await page.getByRole('tab', { name: 'Learn', exact: true }).isVisible());
  await page.getByRole('tab', { name: 'Notes', exact: true }).click();
  await page.getByRole('heading', { name: 'Variable Pattern', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Reference guides', exact: true }).click();
  await page.getByRole('button', { name: /Leetcode Cheatsheet/ }).click();
  await page.getByRole('link', { name: 'Variable Naming Guide', exact: true }).click();
  await page.locator('.problem-heading h1').filter({ hasText: 'Variable Naming Guide' }).waitFor();
  console.log('PASS complete problem surfaces and wiki-linked reference guides');
  await page.getByRole('button', { name: 'Back to library' }).click();
  await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, exportPath);
  await page.getByRole('button', { name: 'Settings and backup', exact: true }).click();
  await page.getByRole('button', { name: 'Export backup', exact: true }).click();
  await page.getByText('Your backup was exported.', { exact: true }).waitFor();
  const exported = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
  assert.equal(exported.progress['leetcode:1'].status, 'completed');
  const editedDuration = exported.sessions.find(s => s.problemId === 'leetcode:1' && s.reflection === 'Check the complement before inserting into seen.').durationMs;
  assert.ok(editedDuration >= 750000 && editedDuration < 760000);
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, invalidPath);
  await page.getByRole('button', { name: 'Restore backup', exact: true }).click();
  await page.getByRole('alert').waitFor();
  const afterInvalid = await page.evaluate(() => window.study.bootstrap());
  assert.deepEqual(afterInvalid.data, exported);
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  await page.getByRole('button', { name: 'Dismiss message', exact: true }).click();
  await page.getByRole('button', { name: 'Open Two Sum', exact: true }).click();
  await page.getByLabel('Problem progress').selectOption('not-started');
  await page.getByRole('button', { name: 'Back to library' }).click();
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false }); }, exportPath);
  await page.getByRole('button', { name: 'Settings and backup', exact: true }).click();
  await page.getByRole('button', { name: 'Restore backup', exact: true }).click();
  await page.getByText('Your backup was restored.', { exact: true }).waitFor();
  assert.deepEqual((await page.evaluate(() => window.study.bootstrap())).data, exported);
  console.log('PASS export, malformed-backup rejection and confirmed restore');
  await app.close();
  app = await launch(); page = await app.firstWindow();
  await page.waitForSelector('.problem-table');
  assert.deepEqual((await page.evaluate(() => window.study.bootstrap())).data, exported);
  for (const [width, height, zoom] of [[1440, 900, 1], [1280, 800, 1.25], [1440, 900, 1.5]]) {
    await app.evaluate(({ BrowserWindow }, size) => { const win = BrowserWindow.getAllWindows()[0]; win.setContentSize(size.width, size.height); win.webContents.setZoomFactor(size.zoom); }, { width, height, zoom });
    await page.waitForTimeout(100);
    assert.ok(await page.locator('.search-input').isVisible());
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2));
  }
  console.log('PASS restart persistence and 100%, 125%, 150% display scaling');
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(ROOT, 'test-results/desktop.json'), JSON.stringify({ passed: true, cases: ['offline library', 'visualizer and custom inputs', 'playback and lifecycle pauses', 'playback message validation', 'isolated visualizer', 'progress and bookmarks', 'notes and reference links', 'history editing', 'backup restore and validation', 'restart persistence', 'display scaling'] }, null, 2));
} finally { await app.close(); }
