import { _electron as electron } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {extractFile} from '@electron/asar';
import {ROOT} from '../scripts/content.mjs';
import {testSingleLineHighlights} from './single-line-highlights.mjs';
if(process.argv.includes('--packaged')&&!process.env.STUDY_TEST_EXE)throw Error('Packaged verification requires STUDY_TEST_EXE to point to the installed executable.');
const profile=fs.mkdtempSync(path.join(ROOT,'.test-data/operations-upgrade-'));
const previous=process.env.STUDY_PREVIOUS_EXE||path.join(ROOT,'.test-data/installer-payload-0.5.5-verified/LeetCode Study.exe');
const version=JSON.parse(fs.readFileSync(path.join(ROOT,'package.json'),'utf8')).version;
async function launch(exe){const env={...process.env,STUDY_DATA_DIR:profile,STUDY_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;if(exe)env.PATH=`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`;const app=await electron.launch({...(exe?{executablePath:exe,args:[]}:{args:[ROOT]}),env});(await app.firstWindow()).setDefaultTimeout(15000);await app.evaluate(({session,BrowserWindow})=>{session.defaultSession.enableNetworkEmulation({offline:true});const win=BrowserWindow.getAllWindows()[0];win.show();win.focus();});return app;}
const lesson=JSON.parse(fs.readFileSync(path.join(ROOT,'visualizer-ui/guided-content-a.json'),'utf8'))[0];
const previousLessons=['a','b'].flatMap(part=>JSON.parse(extractFile(path.join(path.dirname(previous),'resources/app.asar'),path.join('dist','content','visualizer-ui',`guided-content-${part}.json`)).toString()));
const previousLesson=previousLessons.find(item=>item.id===lesson.id);
const contentChanged=previousLesson.version!==lesson.version;
let app=await launch(previous),page=await app.firstWindow();
const previousVersion=await app.evaluate(({app})=>app.getVersion());
try{
 await page.locator('.problem-table').waitFor();
 await page.evaluate(async lesson=>{
  await window.study.selectProblem('leetcode:1');
  await window.study.setProgress('leetcode:1',{status:'in-progress',bookmarked:true,needsReview:true});
  const {data}=await window.study.bootstrap();
  await window.study.editSession(data.sessions.find(item=>item.problemId==='leetcode:1').id,{durationMs:420000,outcome:'solved',reflection:'Preserve this session across the statement-by-statement upgrade.'});
  await window.study.saveDraft('leetcode:1','function twoSum(){return [0,1];}','[[[2,7],9]]');
  await window.study.recordSubmission('leetcode:1','function twoSum(){return [0,1];}',{verdict:'Accepted',passed:1,total:1,durationMs:25,cases:[{name:'Operation upgrade fixture',input:[[2,7],9],actual:[0,1],expected:[0,1],verdict:'Accepted',logs:['Preserve this console output.'],durationMs:25}]});
  const cp=lesson.checkpoints[0];
  await window.study.saveGuidedProgress('leetcode:1',{lessonVersion:lesson.version,caseId:lesson.caseId,runId:'operation-upgrade-check',cursor:cp.afterIndex,answers:{[cp.id]:{attempts:2,choiceId:cp.correctOptionId,hintLevel:1,revealed:false,correct:true}},previousCompletion:{lessonVersion:Math.max(1,lesson.version-1),completedAt:'2026-09-28T17:00:00.000Z'}});
  await window.study.selectProblem(null);
 },previousLesson);
}finally{await app.close();}
const old=JSON.parse(fs.readFileSync(path.join(profile,'study-data.json'),'utf8'));
assert.ok(old.sessions.length&&old.submissions.length,'The upgrade fixture includes populated history and submissions.');
async function open(){await page.locator('.problem-table').waitFor();await page.getByRole('searchbox',{name:'Search problems'}).fill('Two Sum');await page.locator('.problem-table tbody tr').filter({has:page.locator('.number-col',{hasText:/^0*1$/})}).locator('.problem-link').click();await page.getByRole('tab',{name:'Learn',exact:true}).click();const frame=await page.locator('.guided-container iframe').elementHandle().then(e=>e.contentFrame());await frame.waitForFunction(()=>window.studyGuidedController?.progress&&!window.studyGuidedController.busy);return frame;}
async function openVisualizer(number,title){await page.getByRole('button',{name:'Back to library',exact:true}).click();await page.getByRole('searchbox',{name:'Search problems'}).fill(String(number));await page.getByRole('button',{name:`Open ${title}`,exact:true}).click();await page.getByRole('tab',{name:'Visualizer',exact:true}).click();const frame=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(e=>e.contentFrame());await frame.waitForFunction(()=>window.studyWalkthrough);return frame;}
app=await launch(process.env.STUDY_TEST_EXE);page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.locator('.problem-table').waitFor();const bootstrap=await page.evaluate(()=>window.study.bootstrap());assert.equal(bootstrap.version,version);if(process.env.STUDY_TEST_EXE)assert.equal(await app.evaluate(({app})=>app.isPackaged),true);assert.equal(bootstrap.data.version,3);for(const key of ['progress','sessions','drafts','submissions','guided'])assert.deepEqual(bootstrap.data[key],old[key],`${key} survives the upgrade from ${previousVersion}`);
 let frame=await open();assert.equal(await frame.evaluate(()=>studyLessonSource.index()),contentChanged?0:lesson.checkpoints[0].afterIndex);assert.deepEqual((await page.evaluate(()=>window.study.bootstrap())).data.guided['leetcode:1'].answers,contentChanged?{}:old.guided['leetcode:1'].answers);assert.deepEqual((await page.evaluate(()=>window.study.bootstrap())).data.guided['leetcode:1'].previousCompletion,old.guided['leetcode:1'].previousCompletion);assert.equal(await frame.getByLabel('Walkthrough detail').inputValue(),'detailed');await frame.getByLabel('Walkthrough detail').selectOption('compact');
 await page.getByRole('tab',{name:'Visualizer',exact:true}).click();const visual=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(e=>e.contentFrame());await visual.waitForFunction(()=>window.studyWalkthrough?.mode==='compact');await visual.getByLabel('Walkthrough detail').selectOption('detailed');await visual.getByRole('button',{name:'Play',exact:true}).press('Enter');await page.waitForTimeout(400);await visual.getByRole('button',{name:'Pause',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);await page.waitForTimeout(300);assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);
 await visual.getByRole('button',{name:'Next moment',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);await visual.getByRole('button',{name:'Next moment',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),1);
 await page.getByRole('tab',{name:'Learn',exact:true}).click();for(const zoom of [1,1.25,1.5]){await app.evaluate(({BrowserWindow},z)=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1440,960);w.webContents.setZoomFactor(z);w.show();w.focus();},zoom);await page.waitForTimeout(1000);assert.ok(await frame.locator('.study-code').isVisible());assert.equal(await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await frame.locator('.operation-code').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(39, 73, 108)');const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(ROOT,`test-results/operations-desktop-${zoom}.png`),Buffer.from(png,'base64'));}
 await app.close();app=await launch(process.env.STUDY_TEST_EXE);page=await app.firstWindow();frame=await open();assert.equal(await frame.getByLabel('Walkthrough detail').inputValue(),'detailed');assert.equal(await frame.getByRole('button',{name:'Play',exact:true}).getAttribute('aria-pressed'),'false');assert.deepEqual((await page.evaluate(()=>window.study.bootstrap())).data.guided['leetcode:1'].answers,contentChanged?{}:old.guided['leetcode:1'].answers);assert.deepEqual((await page.evaluate(()=>window.study.bootstrap())).data.guided['leetcode:1'].previousCompletion,old.guided['leetcode:1'].previousCompletion);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Back to library',exact:true}).click();await page.getByRole('searchbox',{name:'Search problems'}).fill('26');await page.getByRole('button',{name:'Open Remove Duplicates from Sorted Array',exact:true}).click();await page.getByRole('tab',{name:'Visualizer',exact:true}).click();
 const duplicates=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(element=>element.contentFrame());await duplicates.waitForFunction(()=>window.studyWalkthrough);
 const writeTrace=await duplicates.evaluate(()=>{document.getElementById('custom-input').value='1,1,3';window.loadCustom();const events=[];for(let count=0;count<30&&!document.getElementById('btn-next').disabled;count++){studyLessonAdapter.next();const op=studyWalkthrough.operation,raw=studyLessonSource.read();if(['COMPARE','ADVANCE_LEFT','WRITE'].includes(op.phase))events.push({phase:op.phase,line:op.location.line,locations:op.locations,code:op.code,kind:op.kind,highlight:[...document.querySelectorAll('.operation-code')].map(el=>el.id),left:raw.left,right:raw.right,equal:raw.lastCompareEqual,nums:[...raw.nums]});}return events;});
 assert.ok(writeTrace.some(event=>event.phase==='ADVANCE_LEFT'&&event.line===6&&JSON.stringify(event.locations)==='[6]'&&event.highlight.join(',')==='line-6'&&event.code==='left++;'&&event.left===1&&event.nums[1]===1),'packaged visualizer highlights left++ by itself');
 assert.ok(writeTrace.some(event=>event.phase==='WRITE'&&event.line===7&&JSON.stringify(event.locations)==='[7]'&&event.kind==='copy'&&event.highlight.join(',')==='line-7'&&event.code==='nums[left] = nums[right];'&&event.left===1&&event.nums[1]===3),'packaged visualizer shows the copy after the pointer advance: '+JSON.stringify(writeTrace));
 assert.ok(writeTrace.findIndex(event=>event.phase==='WRITE')>writeTrace.findIndex(event=>event.phase==='ADVANCE_LEFT'),'packaged visualizer preserves action order');
 assert.ok(writeTrace.some(event=>event.phase==='COMPARE'&&event.line===5&&JSON.stringify(event.locations)==='[5]'&&event.right===1&&event.equal===true&&event.highlight.join(',')==='line-5'),'packaged duplicate comparison highlights only the comparison line');
 await app.evaluate(({BrowserWindow})=>{const win=BrowserWindow.getAllWindows()[0];win.setContentSize(1760,1120);win.webContents.setZoomFactor(1);});
 await app.evaluate(({BrowserWindow})=>{const win=BrowserWindow.getAllWindows()[0];win.restore();win.show();win.focus();});
 try{await testSingleLineHighlights(duplicates,async stage=>{const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(ROOT,`test-results/single-line-packaged-${stage}.png`),Buffer.from(png,'base64'));});}
 catch(error){console.error(await duplicates.evaluate(()=>({index:studyLessonSource.index(),mode:studyWalkthrough.mode,phase:studyWalkthrough.operation.phase,playing:document.getElementById("study-play")?.getAttribute("aria-pressed"),hidden:document.hidden,focused:document.hasFocus(),events:window.singleLinePlayback})));console.error(await app.evaluate(({BrowserWindow})=>({focused:BrowserWindow.getAllWindows()[0].isFocused(),visible:BrowserWindow.getAllWindows()[0].isVisible()})));throw error;}
 for(const [number,title]of [[11,'Container With Most Water'],[15,'3Sum'],[35,'Search Insert Position'],[74,'Search a 2D Matrix'],[92,'Reverse Linked List II'],[167,'Two Sum II - Input Array Is Sorted'],[374,'Guess Number Higher or Lower'],[410,'Split Array Largest Sum'],[704,'Binary Search'],[875,'Koko Eating Bananas'],[1011,'Capacity to Ship Packages Within D Days']]){
  const candidate=await openVisualizer(number,title),result=await candidate.evaluate(()=>{const a=studyLessonAdapter,w=studyWalkthrough,s=studyLessonSource,rules=window.studyOperationRules.find(r=>r.id===`leetcode:${s.spec.number}`);let count=0;
   while(!document.getElementById('btn-next').disabled&&count<50000){const pending=s.pendingInstruction?.()||{line:s.readAt(s.index()+1).executedLine},want=[pending.line],prior=s.index();a.next();if(s.index()!==prior+1)throw Error('Instruction did not advance one step');const op=w.operation,actual=[...document.querySelectorAll('.operation-code')].map(el=>Number(el.id.match(/\d+/)?.[0]));
    if(op.location.line!==pending.line||JSON.stringify(actual)!==JSON.stringify(want))throw Error(`Problem ${s.spec.number}: expected ${want}, operation ${op.location.line}, rendered ${actual}`);count++;}
   return {count,complete:document.getElementById('btn-next').disabled};});assert.ok(result.complete&&result.count>0,`packaged ${number} finishes with current-line highlights`);
 }
 const result={passed:true,offline:true,from:previousVersion,to:version,schema:3,packaged:!!process.env.STUDY_TEST_EXE,profile,executable:process.env.STUDY_TEST_EXE||null};fs.writeFileSync(path.join(ROOT,`test-results/operations-${process.env.STUDY_TEST_EXE?'packaged':'desktop'}.json`),JSON.stringify(result,null,2));console.log('PASS upgrade retains all schema-3 records; exact operation lines, playback, zoom and restart');
}finally{await app.close();}
