import { _electron as electron } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {ROOT} from '../scripts/content.mjs';
const profile=fs.mkdtempSync(path.join(ROOT,'.test-data/operations-upgrade-'));
const previous=path.join(ROOT,'.test-data/installer-payload-0.5.3-verified/LeetCode Study.exe');
const version=JSON.parse(fs.readFileSync(path.join(ROOT,'package.json'),'utf8')).version;
async function launch(exe){const env={...process.env,STUDY_DATA_DIR:profile,STUDY_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;if(exe)env.PATH=`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`;const app=await electron.launch({...(exe?{executablePath:exe,args:[]}:{args:[ROOT]}),env});await app.evaluate(({session})=>session.defaultSession.enableNetworkEmulation({offline:true}));return app;}
const lesson=JSON.parse(fs.readFileSync(path.join(ROOT,'visualizer-ui/guided-content-a.json'),'utf8'))[0];
let app=await launch(previous),page=await app.firstWindow();
try{await page.locator('.problem-table').waitFor();await page.evaluate(async lesson=>{await window.study.setProgress('leetcode:1',{status:'in-progress',bookmarked:true,needsReview:true});await window.study.saveDraft('leetcode:1','function twoSum(){return [0,1];}','[[[2,7],9]]');const cp=lesson.checkpoints[0];await window.study.saveGuidedProgress('leetcode:1',{lessonVersion:lesson.version,caseId:lesson.caseId,runId:'operation-upgrade-check',cursor:cp.afterIndex,answers:{[cp.id]:{attempts:2,choiceId:cp.correctOptionId,hintLevel:1,revealed:false,correct:true}}});},lesson);}finally{await app.close();}
const old=JSON.parse(fs.readFileSync(path.join(profile,'study-data.json'),'utf8'));
async function open(){await page.locator('.problem-table').waitFor();await page.getByRole('searchbox',{name:'Search problems'}).fill('Two Sum');await page.locator('.problem-table tbody tr').filter({has:page.locator('.number-col',{hasText:/^0*1$/})}).locator('.problem-link').click();await page.getByRole('tab',{name:'Learn',exact:true}).click();const frame=await page.locator('.guided-container iframe').elementHandle().then(e=>e.contentFrame());await frame.waitForFunction(()=>window.studyGuidedController?.progress&&!window.studyGuidedController.busy);return frame;}
async function openVisualizer(number,title){await page.getByRole('button',{name:'Back to library',exact:true}).click();await page.getByRole('searchbox',{name:'Search problems'}).fill(String(number));await page.getByRole('button',{name:`Open ${title}`,exact:true}).click();await page.getByRole('tab',{name:'Visualizer',exact:true}).click();const frame=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(e=>e.contentFrame());await frame.waitForFunction(()=>window.studyWalkthrough);return frame;}
app=await launch(process.env.STUDY_TEST_EXE);page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.locator('.problem-table').waitFor();const bootstrap=await page.evaluate(()=>window.study.bootstrap());assert.equal(bootstrap.version,version);assert.equal(bootstrap.data.version,3);for(const key of ['progress','sessions','drafts','submissions','guided'])assert.deepEqual(bootstrap.data[key],old[key],`${key} survives the upgrade from 0.5.3`);
 let frame=await open();assert.equal(await frame.evaluate(()=>studyLessonSource.index()),lesson.checkpoints[0].afterIndex);assert.equal(await frame.getByLabel('Walkthrough detail').inputValue(),'detailed');await frame.getByLabel('Walkthrough detail').selectOption('compact');
 await page.getByRole('tab',{name:'Visualizer',exact:true}).click();const visual=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(e=>e.contentFrame());await visual.waitForFunction(()=>window.studyWalkthrough?.mode==='compact');await visual.getByLabel('Walkthrough detail').selectOption('detailed');await visual.getByRole('button',{name:'Play',exact:true}).press('Enter');await page.waitForTimeout(400);await visual.getByRole('button',{name:'Pause',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);await page.waitForTimeout(300);assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);
 await visual.getByRole('button',{name:'Next moment',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),0);await visual.getByRole('button',{name:'Next moment',exact:true}).press('Enter');assert.equal(await visual.evaluate(()=>studyLessonSource.index()),1);
 await page.getByRole('tab',{name:'Learn',exact:true}).click();for(const zoom of [1,1.25,1.5]){await app.evaluate(({BrowserWindow},z)=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1440,960);w.webContents.setZoomFactor(z);w.show();w.focus();},zoom);await page.waitForTimeout(1000);assert.ok(await frame.locator('.study-code').isVisible());assert.equal(await frame.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await frame.locator('.operation-code').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(39, 73, 108)');const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(ROOT,`test-results/operations-desktop-${zoom}.png`),Buffer.from(png,'base64'));}
 await app.close();app=await launch(process.env.STUDY_TEST_EXE);page=await app.firstWindow();frame=await open();assert.equal(await frame.getByLabel('Walkthrough detail').inputValue(),'detailed');assert.equal(await frame.getByRole('button',{name:'Play',exact:true}).getAttribute('aria-pressed'),'false');assert.deepEqual((await page.evaluate(()=>window.study.bootstrap())).data.guided['leetcode:1'].answers,old.guided['leetcode:1'].answers);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'Back to library',exact:true}).click();await page.getByRole('searchbox',{name:'Search problems'}).fill('26');await page.getByRole('button',{name:'Open Remove Duplicates from Sorted Array',exact:true}).click();await page.getByRole('tab',{name:'Visualizer',exact:true}).click();
 const duplicates=await page.locator('.visualizer-container:not(.guided-container) iframe').elementHandle().then(element=>element.contentFrame());await duplicates.waitForFunction(()=>window.studyWalkthrough);
 const writeTrace=await duplicates.evaluate(()=>{document.getElementById('custom-input').value='1,2,2';window.loadCustom();const events=[];for(let count=0;count<30&&!document.getElementById('btn-next').disabled;count++){studyLessonAdapter.next();const op=studyWalkthrough.operation,raw=studyLessonSource.read();if(op.phase==='COMPARE'||op.phase==='WRITE')events.push({phase:op.phase,line:op.location.line,locations:op.locations,code:op.code,kind:op.kind,highlight:[...document.querySelectorAll('.operation-code')].map(el=>el.id),right:raw.right,equal:raw.lastCompareEqual});}return events;});
 assert.ok(writeTrace.some(event=>event.phase==='WRITE'&&event.line===7&&JSON.stringify(event.locations)==='[6,7]'&&event.kind==='copy'&&event.highlight.join(',')==='line-6,line-7'&&event.code==='left++;\nnums[left] = nums[right];'),'packaged visualizer highlights both statements in the write');assert.ok(writeTrace.some(event=>event.phase==='COMPARE'&&event.line===5&&JSON.stringify(event.locations)==='[5]'&&event.right===2&&event.equal===true&&event.highlight.join(',')==='line-5'),'packaged duplicate comparison highlights only the comparison line');
 for(const [number,title]of [[11,'Container With Most Water'],[15,'3Sum'],[35,'Search Insert Position'],[74,'Search a 2D Matrix'],[92,'Reverse Linked List II'],[167,'Two Sum II - Input Array Is Sorted'],[374,'Guess Number Higher or Lower'],[410,'Split Array Largest Sum'],[704,'Binary Search'],[875,'Koko Eating Bananas'],[1011,'Capacity to Ship Packages Within D Days']]){
  const candidate=await openVisualizer(number,title),result=await candidate.evaluate(()=>{const a=studyLessonAdapter,w=studyWalkthrough,s=studyLessonSource,rules=window.studyOperationRules.find(r=>r.id===`leetcode:${s.spec.number}`);let count=0;
   while(!document.getElementById('btn-next').disabled&&count<3000){const frame=a.snapshot(),raw=s.read(),phase=raw.execState||frame.phase,normalized=String(phase).replace(/_/g,' '),mapped=rules.phases?.[phase]??rules.phases?.[normalized]??rules.phases?.[frame.phase],expected=Array.isArray(mapped)?mapped.map(Number):mapped!==undefined&&mapped!==null&&Number.isInteger(Number(mapped))?[Number(mapped)]:[frame.location.line],want=[...new Set(expected)].sort((x,y)=>x-y),prior=s.index();a.next();if(s.index()===prior)throw Error('No progress');const actual=[...document.querySelectorAll('.operation-code')].map(el=>Number(el.id.match(/\d+/)?.[0])).sort((x,y)=>x-y),reported=[...new Set((w.operation.locations||[w.operation.location.line]).map(Number))].sort((x,y)=>x-y);
    if(JSON.stringify(actual)!==JSON.stringify(want)||JSON.stringify(reported)!==JSON.stringify(want))throw Error(`Problem ${s.spec.number} ${s.spec.mode}, phase ${phase}, trace line ${frame.location.line}: expected ${want}, operation ${reported}, rendered ${actual}`);count++;}
   return {count,complete:document.getElementById('btn-next').disabled};});assert.ok(result.complete&&result.count>0,`packaged ${number} finishes with current-line highlights`);
 }
 const result={passed:true,offline:true,from:'0.5.3',to:version,schema:3,packaged:!!process.env.STUDY_TEST_EXE,profile,installerExecuted:false};fs.writeFileSync(path.join(ROOT,`test-results/operations-${process.env.STUDY_TEST_EXE?'packaged':'desktop'}.json`),JSON.stringify(result,null,2));console.log('PASS upgrade retains all schema-3 records; exact operation lines, playback, zoom and restart');
}finally{await app.close();}
