import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {_electron as electron} from 'playwright';
import {ROOT} from '../scripts/content.mjs';
fs.mkdirSync(path.join(ROOT,'.test-data'),{recursive:true});fs.mkdirSync(path.join(ROOT,'test-results'),{recursive:true});
const profile=fs.mkdtempSync(path.join(ROOT,'.test-data/panel-layout-native-')),env={...process.env,STUDY_DATA_DIR:profile,STUDY_HEADLESS:'0'};delete env.ELECTRON_RUN_AS_NODE;delete env.STUDY_DEV_URL;
let app,page,entries;const errors=[],checks=[];
async function launch(){app=await electron.launch({...(env.STUDY_TEST_EXE?{executablePath:env.STUDY_TEST_EXE,args:[]}:{args:[ROOT]}),env});page=await app.firstWindow();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));await page.locator('.problem-table').waitFor();entries=(await page.evaluate(()=>window.study.bootstrap())).catalog.entries;await app.evaluate(({BrowserWindow})=>{const win=BrowserWindow.getAllWindows()[0];if(win.isMinimized())win.restore();win.setSize(1480,940);win.webContents.setZoomFactor(1);win.show();win.focus();});}
async function open(number,tab='Visualizer'){await page.getByTitle('Problem library',{exact:true}).click();await page.getByRole('searchbox',{name:'Search problems'}).fill(String(number));await page.getByRole('button',{name:`Open ${entries.find(e=>e.number===number).title}`,exact:true}).click();await page.getByRole('tab',{name:tab,exact:true}).click();}
async function frame(guided=false){const iframe=page.locator(guided?'.guided-container iframe':'.visualizer-container:not(.guided-container) iframe');const host=await (await iframe.elementHandle()).contentFrame();await host.waitForFunction(()=>window.studyPanelLayout);return host;}
const layout=host=>host.evaluate(()=>((window.studyPanelLayout)||document.querySelector('.debug-panel-workspace')?.studyPanelLayout).snapshot());
const geometry=r=>[r.x,r.y,r.width,r.height].map(n=>Math.round(n*100)/100);
const settle=host=>host.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
async function show(host,title){await host.locator('.study-panels-menu>summary').click();await host.getByRole('button',{name:`Show ${title}`,exact:true}).click();await settle(host);}
async function move(host,id,title,dx,dy){await show(host,title);const handle=host.locator(`[data-study-panel=${id}] .study-panel-title`);const box=await handle.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+dx,box.y+box.height/2+dy,{steps:8});await page.mouse.up();await settle(host);}
async function capture(file){const png=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(ROOT,'test-results',file),Buffer.from(png,'base64'));}
const sources={1:'function twoSum(nums,target) {\n const seen = new Map();\n for(let i=0;i<nums.length;i++) {\n  if(seen.has(target-nums[i])) return [seen.get(target-nums[i]),i];\n  seen.set(nums[i],i);\n }\n}',21:'function mergeTwoLists(list1,list2) {\n const chosen = list1;\n return chosen;\n}'};
async function debug(number){await page.evaluate(({id,source})=>window.study.saveDraft(id,source,'[]'),{id:'leetcode:'+number,source:sources[number]});await open(number,'Code');await page.getByRole('textbox',{name:'JavaScript solution',exact:true}).waitFor();await page.getByRole('button',{name:'Debug',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.debug-status.paused'));await page.locator('[data-study-panel=code] .monaco-editor').waitFor();}
async function closeDebug(){const immediate=page.getByRole('button',{name:'Close debugger and return to code',exact:true});if(await immediate.isVisible())await immediate.click();else await page.getByRole('button',{name:/Stop \/ edit/}).click();await page.locator('.debug-workspace').waitFor({state:'detached'});}
try{
 await launch();await open(206);let reference=await frame();await reference.waitForFunction(()=>window.studyLessonAdapter?.objectSnapshot);const index=await reference.evaluate(()=>studyLessonSource.index());const initial=(await layout(reference)).panels.code;
 await move(reference,'code','Reference Code',-70,30);const refSaved=geometry((await layout(reference)).panels.code);assert.ok(refSaved[0]<initial.x-60);assert.equal(await reference.evaluate(()=>studyLessonSource.index()),index);
 await reference.getByRole('button',{name:'Resize Reference Code',exact:true}).click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const refSize=geometry((await layout(reference)).panels.code);
 await open(21);reference=await frame();assert.deepEqual(geometry((await layout(reference)).panels.code),refSize);checks.push('Reference pointer dragging, keyboard sizing and shared problem layout');
 await page.getByRole('tab',{name:'Learn',exact:true}).click();let guided=await frame(true);await guided.waitForFunction(()=>window.studyGuidedController?.progress);const progress=await guided.evaluate(()=>JSON.stringify(studyGuidedController.progress));await move(guided,'question','Question',20,25);const learnSaved=geometry((await layout(guided)).panels.question);assert.equal(await guided.evaluate(()=>JSON.stringify(studyGuidedController.progress)),progress);checks.push('Learn panels preserve predictions and have separate saved geometry');
 await debug(1);const debugIndex=await page.locator('.debug-timeline>span').innerText();await show(page,'Your Code');await page.evaluate(()=>{window.panelTestEditor=document.querySelector('.debug-source .monaco-editor');});
 await move(page,'code','Your Code',-65,25);await page.getByRole('button',{name:'Resize Your Code',exact:true}).click();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const debugSaved=geometry((await layout(page)).panels.code);
 assert.equal(await page.locator('.debug-timeline>span').innerText(),debugIndex);assert.equal(await page.evaluate(()=>window.panelTestEditor===document.querySelector('.debug-source .monaco-editor')),true,'Moving a window preserves the mounted editor');
 await show(page,'Objects');const objectsBefore=geometry((await layout(page)).panels.objects);await page.getByRole('button',{name:'Expand nums',exact:true}).click();assert.equal((await layout(page)).maximized,'objects');assert.ok(await page.locator('.debug-source').isHidden());await page.keyboard.press('Escape');await settle(page);assert.equal((await layout(page)).maximized,null);assert.deepEqual(geometry((await layout(page)).panels.objects),objectsBefore);assert.equal(await page.locator('.debug-timeline>span').innerText(),debugIndex);
 await show(page,'Call Stack');assert.ok(await page.locator('.viz-stack>button').first().isVisible());await show(page,'Variables');assert.ok(await page.locator('.viz-variable').count()>0);
 await capture('panel-layout-debug.png');await closeDebug();await debug(21);assert.deepEqual(geometry((await layout(page)).panels.code),debugSaved);await closeDebug();checks.push('Debug movement preserves worker checkpoint, editor instance, scoped objects and cross-problem layout');
 const prefs=await page.evaluate(()=>localStorage.getItem('study.panelLayout.v1.debug'));await app.close();app=null;
 await launch();assert.equal(await page.evaluate(()=>localStorage.getItem('study.panelLayout.v1.debug')),prefs);await open(206);reference=await frame();assert.deepEqual(geometry((await layout(reference)).panels.code),refSize);
 await page.getByRole('tab',{name:'Learn',exact:true}).click();guided=await frame(true);assert.deepEqual(geometry((await layout(guided)).panels.question),learnSaved);
 await debug(1);assert.deepEqual(geometry((await layout(page)).panels.code),debugSaved);const data=(await page.evaluate(()=>window.study.bootstrap())).data;assert.equal(data.drafts['leetcode:1'].source,sources[1]);assert.equal(data.submissions.length,0);checks.push('All three layouts survive actual application restart; drafts remain intact and no submission is created');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(ROOT,'test-results/panel-layout-desktop.json'),JSON.stringify({passed:true,packaged:!!env.STUDY_TEST_EXE,executable:env.STUDY_TEST_EXE||null,checks},null,2));for(const check of checks)console.log('PASS '+check);
}catch(error){if(app)await capture('panel-layout-native-failure.png').catch(()=>{});fs.writeFileSync(path.join(ROOT,'test-results/panel-layout-desktop.json'),JSON.stringify({passed:false,checks,error:error.stack,errors},null,2));throw error;}finally{if(app)await app.close();}
