import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import type { VisualizationFrame, VisualObject, VisualValue, VisualLocation } from '../../shared/visualization';
import { valueText } from '../../shared/visualization';
import type { ObjectFocus } from '../../shared/object-view';
import '../../visualizer-ui/learning.css';
import ObjectView from './ObjectView';
import {StudyPanel,usePanelLayout} from './PanelWorkspace';

export function Legend(){return <div className="viz-legend" aria-label="Visual legend"><span className="active">● Active</span><span className="read">◉ Read</span><span className="changed">◆ Changed</span><span className="complete">✓ Result</span><span className="path">↗ Reference / path</span></div>;}
function NodeGraph({nodes,frame,onSelect}:{nodes:VisualObject[];frame:VisualizationFrame;onSelect:(id:string)=>void}){
  const ids=new Set(nodes.map(n=>n.id)),byId=new Map(frame.objects.map(n=>[n.id,n]));
  const edges=nodes.flatMap(n=>n.entries.flatMap(e=>{if(!e.value||typeof e.value!=='object'||!('ref'in e.value))return [];if(ids.has(e.value.ref))return [{from:n.id,to:e.value.ref,key:e.key}];const neighbors=e.key==='neighbors'?byId.get(e.value.ref):undefined;return neighbors?.entries.flatMap(child=>child.value&&typeof child.value==='object'&&'ref'in child.value&&ids.has(child.value.ref)?[{from:n.id,to:child.value.ref,key:'neighbor'}]:[])||[];}));
  const positions=new Map<string,{x:number;y:number}>(),visited=new Set<string>();let column=0;
  function layout(id:string,depth:number){if(visited.has(id))return;visited.add(id);const children=edges.filter(e=>e.from===id);if(nodes.some(n=>n.kind==='tree')){const left=children.find(e=>e.key==='left');if(left)layout(left.to,depth+1);}positions.set(id,{x:60+column++*85,y:50+depth*100});for(const edge of children)layout(edge.to,depth+1);}
  const roots=nodes.filter(n=>!edges.some(e=>e.to===n.id));for(const node of roots.length?roots:nodes.slice(0,1))layout(node.id,0);for(const node of nodes)if(!visited.has(node.id))layout(node.id,0);
  if(nodes.every(n=>n.kind==='list'))nodes.forEach((node,i)=>positions.set(node.id,{x:65+i*130,y:65}));
  if(nodes.some(n=>n.kind==='graph')){const radius=Math.max(150,nodes.length*14);nodes.forEach((node,i)=>positions.set(node.id,{x:radius+60+radius*Math.cos(i/nodes.length*Math.PI*2),y:radius+60+radius*Math.sin(i/nodes.length*Math.PI*2)}));}
  const width=Math.max(350,...[...positions.values()].map(p=>p.x+60)),height=Math.max(180,...[...positions.values()].map(p=>p.y+60));
  return <svg className="viz-node-graph" width={width} height={height} role="img" aria-label="Node relationships"><defs><marker id="debug-node-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#b99cfa"/></marker></defs>{edges.map((edge,i)=>{const a=positions.get(edge.from)!,b=positions.get(edge.to)!;return <g key={i}><path d={a===b?`M${a.x+22},${a.y}c65,-65 65,65 0,0`:`M${a.x},${a.y+22} Q${a.x},${b.y-32} ${b.x},${b.y-26}`} fill="none" stroke="#b99cfa" strokeWidth="2" markerEnd="url(#debug-node-arrow)"/><text x={(a.x+b.x)/2+8} y={(a.y+b.y)/2} fill="#b7a3d9" fontSize="10">{edge.key}</text></g>;})}{nodes.map(node=>{const p=positions.get(node.id)!,changed=frame.changes.some(c=>c.objectId===node.id),read=frame.reads.some(r=>r.objectId===node.id),names=(frame.stack.at(-1)?.variables||[]).filter(v=>v.value&&typeof v.value==='object'&&'ref'in v.value&&v.value.ref===node.id).map(v=>v.name).join(', ');return <g key={node.id} data-motion-key={`node:${node.id}`} className={`viz-graph-node ${changed?'changed':read?'read':''}`} transform={`translate(${p.x},${p.y})`} role="button" tabIndex={0} aria-label={`Inspect ${node.id}`} onClick={()=>onSelect(node.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect(node.id);}}><circle r="25"/><text textAnchor="middle" dy="5">{valueText(node.entries.find(e=>e.key==='val')?.value)}</text><text className="viz-node-alias" textAnchor="middle" y="-35">{names.slice(0,24)}</text>{(changed||read)&&<text className="viz-role-symbol" x="22" y="-22">{changed?"\u25c6":"\u25c9"}</text>}<text className="viz-node-id" textAnchor="middle" y="43">{node.id}</text></g>;})}</svg>;
}
function HeapView({object,frame,onSelect}:{object:VisualObject;frame:VisualizationFrame;onSelect:(id:string)=>void}){
  const entries=object.entries.filter(e=>/^\d+$/.test(e.key)),depth=Math.floor(Math.log2(Math.max(1,entries.length))),width=Math.max(300,2**depth*65),height=(depth+1)*90+25;
  const point=(index:number)=>{const level=Math.floor(Math.log2(index+1)),offset=index-(2**level-1);return {x:(offset+.5)*width/(2**level),y:40+level*90};};
  return <svg className="viz-heap-graph" width={width} height={height} role="img" aria-label="Array viewed as a binary heap">{entries.slice(1).map(entry=>{const index=Number(entry.key),a=point((index-1)>>1),b=point(index);return <path key={entry.key} d={`M${a.x},${a.y+22}L${b.x},${b.y-22}`} stroke="#7892b5"/>;})}{entries.map(entry=>{const p=point(Number(entry.key)),changed=frame.changes.some(c=>c.objectId===object.id&&c.key===entry.key);return <g key={entry.key} className={`viz-graph-node ${changed?'changed':''}`} transform={`translate(${p.x},${p.y})`} data-object={object.id} data-entry={entry.key}><circle r="24"/><text textAnchor="middle" dy="5" onClick={()=>{if(entry.value&&typeof entry.value==='object'&&'ref'in entry.value)onSelect(entry.value.ref);}}>{valueText(entry.value)}</text><text textAnchor="middle" y="40" className="viz-node-id">[{entry.key}]</text></g>;})}</svg>;
}
export default function FrameView({frame,previousFrame,operationFrame=frame,moment=2,onSelectLocation,onObjectFocusChange,objectTextSize,onObjectTextSizeChange}:{frame:VisualizationFrame;previousFrame?:VisualizationFrame;operationFrame?:VisualizationFrame;moment?:number;onSelectLocation?:(location:VisualLocation)=>void;onObjectFocusChange?:(focus:ObjectFocus|null)=>void;objectTextSize?:number;onObjectTextSizeChange?:(size:number)=>void}){
  const layout=usePanelLayout();
  const [layoutEpoch,setLayoutEpoch]=useState(0);
  const [objectFocus,setObjectFocus]=useState<ObjectFocus|null>(null),[localObjectTextSize,setLocalObjectTextSize]=useState(16);
  const [reducedMotion,setReducedMotion]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{const preference=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReducedMotion(preference.matches);preference.addEventListener('change',change);return()=>preference.removeEventListener('change',change);},[]);
  const [selected,setSelected]=useState<string|null>(null),[stackId,setStackId]=useState<number|null>(null),[zoom,setZoom]=useState(1),[expanded,setExpanded]=useState(false),[views,setViews]=useState<Record<string,string>>({}),[pins,setPins]=useState<string[]>([]),[motion,setMotion]=useState(true),[flows,setFlows]=useState<{path:string;label:string}[]>([]);
  const frameHost=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null),scene=useRef<HTMLDivElement>(null),previous=useRef(new Map<string,DOMRect>()),pan=useRef<{x:number;y:number;left:number;top:number}|null>(null);
  useEffect(()=>{setStackId(null);},[frame.index]);
  useEffect(()=>layout?.subscribe(()=>{previous.current.clear();setLayoutEpoch(value=>value+1);}),[layout]);
  useEffect(()=>{const host=stage.current?.closest('.study-panels-host');host?.classList.toggle('study-no-motion',!motion);return()=>host?.classList.remove('study-no-motion');},[motion,layoutEpoch]);
  useLayoutEffect(()=>{
    const host=frameHost.current,tabs=host?.querySelector<HTMLElement>('.study-object-view-tabs');if(!host||!tabs)return;
    const measure=()=>host.style.setProperty('--study-object-tabs-height',`${Math.ceil(tabs.getBoundingClientRect().height)}px`);
    measure();const observer=new ResizeObserver(measure);observer.observe(tabs);return()=>observer.disconnect();
  },[]);
  useLayoutEffect(()=>{
    const animations:Animation[]=[];const next=new Map<string,DOMRect>();
    if(!motion||reducedMotion){previous.current.clear();return;}
    for(const element of stage.current?.querySelectorAll<HTMLElement>('[data-motion-key]')||[]){const key=element.dataset.motionKey!,rect=element.getBoundingClientRect(),old=previous.current.get(key);if(old&&(Math.abs(old.x-rect.x)>2||Math.abs(old.y-rect.y)>2))animations.push(element.animate([{translate:`${(old.x-rect.x)/zoom}px ${(old.y-rect.y)/zoom}px`},{translate:'0 0'}],{duration:240,easing:'ease-out'}));next.set(key,rect);}previous.current=next;return()=>animations.forEach(a=>a.cancel());
  },[frame.index,zoom,motion,reducedMotion,layoutEpoch]);
  useLayoutEffect(()=>{
    function draw(){
      if(!scene.current)return;const origin=scene.current.getBoundingClientRect(),paths:{path:string;label:string}[]=[];
      const cell=(objectId:string,key:string)=>scene.current!.querySelector<HTMLElement>(`[data-object="${CSS.escape(objectId)}"][data-entry="${CSS.escape(key)}"]`);
      for(const link of moment===2?(operationFrame.operations||[]).flatMap(op=>op.links||[]):[]){const from=cell(link.from.objectId,link.from.key),to=cell(link.to.objectId,link.to.key);if(!from||!to)continue;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=(a.x+a.width/2-origin.x)/zoom,y1=(a.y-origin.y)/zoom,x2=(b.x+b.width/2-origin.x)/zoom,y2=(b.y-origin.y)/zoom,top=Math.min(y1,y2)-18;paths.push({path:`M${x1},${y1}C${x1},${top} ${x2},${top} ${x2},${y2}`,label:link.label});}
      setFlows(old=>JSON.stringify(old)===JSON.stringify(paths)?old:paths);
    }
    draw();const observer=new ResizeObserver(draw);if(scene.current)observer.observe(scene.current);return()=>observer.disconnect();
  },[frame,operationFrame,moment,zoom,expanded,views,layoutEpoch]);
  const activeFrame=frame.stack.find(s=>s.id===stackId)||frame.stack.at(-1),objects=frame.objects.filter(o=>o.kind!=='function'),byId=new Map(frame.objects.map(o=>[o.id,o]));
  const variables=(activeFrame?.variables||[]).filter(v=>!(typeof v.value==='object'&&v.value&&('special'in v.value&&['not initialized','global object'].includes(v.value.special)||'ref'in v.value&&byId.get(v.value.ref)?.kind==='function')));
  function select(id:string){layout?.show('diagram');setSelected(id);setExpanded(true);requestAnimationFrame(()=>stage.current?.querySelector<HTMLElement>(`[data-object-id="${id}"]`)?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'auto'}));}
  const renderValue=(value:VisualValue)=>value!==null&&typeof value==='object'&&'ref'in value?<button className="viz-reference" onClick={()=>select(value.ref)} title={`Inspect ${value.ref}`}>↗ {byId.get(value.ref)?.kind==='function'?byId.get(value.ref)?.label:value.ref}</button>:<span>{valueText(value)}</span>;
  const graphNodes=objects.filter(o=>['tree','list','graph'].includes(o.kind)).slice(0,200);
  const displayObjects=expanded?objects:objects.slice(0,24);
  const aliases=(id:string)=>variables.filter(v=>v.value&&typeof v.value==='object'&&'ref'in v.value&&v.value.ref===id).map(v=>v.name).join(', ');
  return <div ref={frameHost} className={`viz-frame viz-panel-frame ${motion?'':'study-no-motion'} ${objectFocus?'study-object-focus':''}`}>
    <StudyPanel id="operation" title="Current Operation"><section className={`viz-explanation${objectFocus?' debug-object-instruction':''}`} aria-label="Current operation" title={objectFocus?(operationFrame.operations?.[0]?.[moment===0?'focus':moment===1?'action':'result']||operationFrame.action):undefined}><div className="viz-eyebrow">{operationFrame.phase==='before'?'NEXT STATEMENT':'CHECKPOINT'} · LINE {operationFrame.location.line} · {['FOCUS','ACTION','RESULT'][moment]}</div>{operationFrame.operations?.length?<ul className="operation-observations">{operationFrame.operations.slice(0,objectFocus?1:8).map((op,i)=><li key={i} data-kind={op.kind}><button className="operation-source" onClick={()=>onSelectLocation?.(op.location)}>Line {op.location.line}</button> <b>{op.kind==='lookup'?'Check':op.kind==='write'?'Store':op.kind}</b> {op[moment===0?'focus':moment===1?'action':'result']}</li>)}{!objectFocus&&operationFrame.operations.length>8&&<li>{operationFrame.operations.length-8} further observations; inspect the values below.</li>}</ul>:<strong>{operationFrame.action}</strong>}{!objectFocus&&<details className="viz-step-help"><summary>About this checkpoint</summary><p>{operationFrame.explanation}</p></details>}</section>
    <Legend/>
    {frame.changes.length>0&&<div className="viz-changes" aria-label="What changed">{frame.changes.slice(0,12).map((change,i)=><button key={`${frame.index}-${i}`} onClick={()=>change.objectId&&select(change.objectId)} className="viz-change"><b>{change.name}</b> {valueText(change.before)} <span>→</span> {valueText(change.after)}</button>)}{frame.changes.length>12&&<span>+{frame.changes.length-12} more changes in variables</span>}</div>}
    </StudyPanel>
    <StudyPanel id="variables" title="Variables"><div className="viz-variables">{[...variables].sort((a,b)=>Number(pins.includes(b.id))-Number(pins.includes(a.id))).map(variable=><div key={variable.id} className={`viz-variable ${frame.changes.some(c=>c.name===variable.name)?'changed':''}`}><button aria-pressed={pins.includes(variable.id)} title="Pin variable" onClick={()=>setPins(p=>p.includes(variable.id)?p.filter(id=>id!==variable.id):[...p,variable.id])}>{pins.includes(variable.id)?'◆':'◇'}</button><b>{variable.name}</b>{renderValue(variable.value)}</div>)}</div>
    </StudyPanel>
    <StudyPanel id="objects" title="Objects" bodyClassName="debug-visual-pane">
    <div id="debug-objects-panel" role="region" aria-label="Debug objects"><ObjectView frame={frame} previousFrame={previousFrame} selectedFrameId={activeFrame?.id} active textSize={objectTextSize??localObjectTextSize} onTextSizeChange={onObjectTextSizeChange||setLocalObjectTextSize} onFocusChange={next=>{setObjectFocus(next);layout?.focus('objects',!!next);onObjectFocusChange?.(next);}} onSelectFrame={id=>{setStackId(id);const selected=frame.stack.find(call=>call.id===id);if(selected)onSelectLocation?.(selected.location);}}/></div>
    </StudyPanel>
    <StudyPanel id="diagram" title="Diagrams" bodyClassName="debug-visual-pane"><div id="debug-diagrams-panel" role="region" aria-label="Debug diagrams">
    <div className="viz-view-tools"><span>Memory & data structures</span><button onClick={()=>setZoom(z=>Math.max(.25,z-.15))} aria-label="Zoom out diagram">−</button><output>{Math.round(zoom*100)}%</output><button onClick={()=>setZoom(z=>Math.min(2,z+.15))} aria-label="Zoom in diagram">+</button><button onClick={()=>{setZoom(1);requestAnimationFrame(()=>{if(stage.current&&scene.current){setZoom(Math.max(.25,Math.min(1,(stage.current.clientWidth-30)/scene.current.scrollWidth)));stage.current.scrollTop=0;stage.current.scrollLeft=0;}});}}>Fit</button><button aria-pressed={motion} onClick={()=>setMotion(v=>!v)}>Motion {motion?'on':'off'}</button><small>Alt + drag to pan · Highlights mark reads and changes. Arrows show explicit relationships.</small></div>
    <div className="viz-stage" ref={stage} onPointerDown={e=>{if(!e.altKey&&e.target!==e.currentTarget&&e.target!==scene.current)return;e.preventDefault();pan.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(pan.current){e.currentTarget.scrollLeft=pan.current.left+pan.current.x-e.clientX;e.currentTarget.scrollTop=pan.current.top+pan.current.y-e.clientY;}}} onPointerUp={()=>pan.current=null} onLostPointerCapture={()=>pan.current=null}>
      <div className="viz-scene" ref={scene} style={{zoom}}>
        <svg className="viz-dataflows" aria-label="Reads and changes" width="100%" height="100%"><defs><marker id="debug-data-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#7dd3e8"/></marker></defs>{flows.map((flow,i)=><path key={i} className="study-transfer" d={flow.path} markerEnd="url(#debug-data-arrow)"><title>{flow.label}</title></path>)}</svg>
        {!!graphNodes.length&&<NodeGraph nodes={graphNodes} frame={frame} onSelect={select}/>}
        {!objects.length&&<div className="viz-empty">Data structures appear here as your code creates them. Scalar values are shown above.</div>}
        {displayObjects.map(object=>{const matrix=object.kind==='array'&&object.entries.length>0&&object.entries.every(e=>e.value!==null&&typeof e.value==='object'&&'ref'in e.value&&byId.get(e.value.ref)?.kind==='array');const view=views[object.id]|| (matrix?'matrix':object.kind);return <section key={object.id} data-motion-key={object.id} data-object-id={object.id} className={`viz-object ${selected===object.id?'selected':''} ${moment<2&&operationFrame.operations?.some(op=>op.targets?.some(t=>t.objectId===object.id))?'operation-object-focus':''}`}>
          <header><strong>{aliases(object.id)||object.label}</strong><small>{object.id}{object.size!==undefined?` · ${object.size} items`:''}</small>{object.kind==='array'&&<select aria-label={`View ${object.id} as`} value={view} onChange={e=>setViews(v=>({...v,[object.id]:e.target.value}))}><option value="array">Array</option>{matrix&&<option value="matrix">Matrix</option>}<option value="heap">Heap</option></select>}</header>
          {view==='matrix'?<div className="viz-matrix">{object.entries.map(row=>{const rowObject=byId.get((row.value as {ref:string}).ref)!;return <div className="viz-array" key={row.key}><small>{row.key}</small>{rowObject.entries.map(cell=><div key={cell.key} data-object={rowObject.id} data-entry={cell.key} className={`viz-cell ${frame.changes.some(c=>c.objectId===rowObject.id&&c.key===cell.key)?'changed':frame.reads.some(r=>r.objectId===rowObject.id&&r.key===cell.key)?'read':''}`}><small>[{row.key},{cell.key}]</small>{renderValue(cell.value)}</div>)}</div>;})}</div>:view==='heap'?<HeapView object={object} frame={frame} onSelect={select}/>:<div className={['array','set'].includes(object.kind)?'viz-array':'viz-properties'}>{object.entries.map(entry=><div key={entry.key} data-object={object.id} data-entry={entry.key} data-motion-key={`${object.id}:${entry.key}`} className={`viz-cell ${frame.changes.some(c=>c.objectId===object.id&&c.key===entry.key)?'changed':frame.reads.some(r=>r.objectId===object.id&&r.key===entry.key)?'read':''}`}><small>{entry.keyValue!==undefined?renderValue(entry.keyValue):entry.key}</small><div key={valueText(entry.value)}>{renderValue(entry.value)}</div></div>)}{!object.entries.length&&<span className="viz-empty">Empty</span>}</div>}
          {object.truncated&&<small className="viz-truncation">Additional entries omitted from this snapshot.</small>}
        </section>;})}
        {variables.filter(v=>typeof v.value==='string'&&v.value.length>0).map(variable=><section key={variable.id} className="viz-object"><header><strong>{variable.name}</strong><small>Indexed string · UTF-16</small></header><div className="viz-array">{(variable.value as string).split('').slice(0,200).map((char,i)=><div className="viz-cell" key={i}><small>{i}</small>{char===' '?'␣':char}</div>)}</div>{(variable.value as string).length>200&&<small className="viz-truncation">First 200 code units shown.</small>}</section>)}
        {!expanded&&objects.length>24&&<button className="viz-expand" onClick={()=>setExpanded(true)}>Show all {objects.length} structures</button>}
      </div>
    </div>
    </div>
    </StudyPanel>
    <StudyPanel id="stack" title="Call Stack">
    {frame.truncated&&<p className="viz-truncation">This state exceeds the display limit. Omitted values are labeled; execution is unaffected.</p>}
    <section className="viz-stack"><h3>Call stack <small>Top frame first</small></h3>{[...frame.stack].reverse().map((item,i)=><button key={item.id} className={activeFrame?.id===item.id?'selected':''} onClick={()=>{setStackId(item.id);onSelectLocation?.(item.location);}}><span>{i===0?'▶':'↳'} {item.name}</span><small>Line {item.location.line}</small></button>)}</section>
    </StudyPanel>
    {!!frame.logs.length&&<StudyPanel id="console" title="Console"><details className="viz-console" open><summary>Console ({frame.logs.length})</summary><pre>{frame.logs.join('\n')}</pre></details></StudyPanel>}
  </div>;
}
